# Generated by Django 4.2.3 on 2024-03-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnipost',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='types',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
