# Generated by Django 4.2.3 on 2024-03-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_student_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='sid',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sid',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='placeholder_password', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='placeholder_password', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
