# Generated by Django 5.0.3 on 2024-03-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_username_mark_sid_remove_student_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='attendence',
            new_name='attendance',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='sid',
            new_name='student',
        ),
    ]
