# Generated by Django 5.0.3 on 2024-03-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_types_student_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='student',
            new_name='sid',
        ),
    ]
