# Generated by Django 5.0.3 on 2024-03-18 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_rename_sid_mark_name_remove_student_sid_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
